[package]
name = "davyjones"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.117" }
time = { version = "0.3.36", features = ["serde", "parsing", "formatting"] }
